name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows-installer:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Download Node.js runtime
      run: |
        Invoke-WebRequest -Uri "https://nodejs.org/dist/v18.17.0/win-x64/node.exe" -OutFile "node.exe"

    - name: Create installer directory
      run: mkdir installer

    - name: Create app icon (placeholder)
      run: |
        # Create a simple ICO file placeholder
        echo "Placeholder icon" > installer/app.ico

    - name: Create LICENSE file
      run: |
        echo "MIT License - Cottage Tandoori Printer Helper" > installer/LICENSE
        echo "Copyright (c) 2025 Cottage Tandoori Restaurant" >> installer/LICENSE
        echo "" >> installer/LICENSE
        echo "Permission is hereby granted, free of charge, to any person obtaining a copy" >> installer/LICENSE
        echo "of this software and associated documentation files (the Software), to deal" >> installer/LICENSE
        echo "in the Software without restriction, including without limitation the rights" >> installer/LICENSE
        echo "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell" >> installer/LICENSE
        echo "copies of the Software, and to permit persons to whom the Software is" >> installer/LICENSE
        echo "furnished to do so, subject to the following conditions:" >> installer/LICENSE
        echo "" >> installer/LICENSE
        echo "The above copyright notice and this permission notice shall be included in all" >> installer/LICENSE
        echo "copies or substantial portions of the Software." >> installer/LICENSE

    - name: Copy files to installer directory
      run: |
        copy server.js installer/
        copy service-install.js installer/
        copy service-uninstall.js installer/
        copy package.json installer/
        copy test-service.js installer/
        copy node.exe installer/
        xcopy node_modules installer\node_modules\ /E /I /H /Y

    - name: Build NSIS Installer
      uses: joncloud/makensis-action@v4.1
      with:
        script-file: installer/installer.nsi
        arguments: "/V3"

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: installer/cottage-tandoori-printer-helper-installer.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: installer/cottage-tandoori-printer-helper-installer.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
